
INSERT INTO myDb.mySchema.FINAL_FRIENDS_DATA( 
SELECT
 YEAR_OF_PASSING AS PASSING_YEAR,
 FIRST_NAME,
 LAST_NAME,
 SUM(TOTAL_MARKS) AS TOTAL_MARKS,
 SUM(MARKS) AS MARKS_OBTAINED,
 CASE
 WHEN SUM(MARKS)>=300 THEN 'A'
 WHEN SUM(MARKS)>=200 THEN 'B'
 WHEN SUM(MARKS)>=100 THEN 'C'
 ELSE 'U'
 END AS FINAL_GRADE
FROM myDb.mySchema.INTER_FRIENDS_DATA
GROUP BY PASSING_YEAR, FIRST_NAME, LAST_NAME
);